### PR TITLE
Compatibility with React Native 0.16 and up.

### PR DESCRIPTION
**Pull request by juankiz**
Removes RCTSparseArray dependency.

### CODE REVIEW

**Comment by juankiz** [comment]
Hey @qrush do you have any comments on my pr? :)

**Comment by qrush** [comment]
Nice. If you want to be the primary fork, I can point it to you. I probably won't be shipping anything with this.

**Comment by juankiz** [comment]
Sure! Sounds fun :dancers:

**Comment by scottdixon-zz** [comment]
Thanks for the fix @juankiz

**Comment by qrush** [comment]
I added you as a collaborator, not sure how to reparent. :ship:

**Comment by juankiz** [comment]
How did I miss this for so long? So sorry @qrush 😁

**Pull request merged**
